# Génération des composants Bokeh
from bokeh.embed import components

#Need a plot generated by my python file mainYear or mainAuthor and create a file html for later use.
def createFile(plot):
    script, div = components(plot)

    # Étape 4 : Écrire le contenu dans un fichier HTML
    custom_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Bokeh Plot</title>
        <style>
        html, body {{
            box-sizing: border-box;
            display: flow-root;
            height: 100%;
            margin: 0;
            padding: 0;
        }}
        </style>
        <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-3.5.2.min.js"></script>
        <script type="text/javascript">
            Bokeh.set_log_level("info");
        </script>
    </head>
    <body>
        <h1>Mon Graphique</h1>

        {div}  <!-- Insérer la div générée par Bokeh ici -->

        {script}
        
    </body>
    </html>
    """

    with open('mon_graphique.html', 'w') as f:
        f.write(custom_html)

    print("Le fichier 'mon_graphique.html' a été créé avec succès.")
